# Generated by Django 2.1.4 on 2018-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sal_delay',
            field=models.IntegerField(default=400),
        ),
    ]
