# Generated by Django 2.1.3 on 2019-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190107_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_map',
            field=models.TextField(blank=True),
        ),
    ]
